version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - mikeharris-des
    labels:
      - dependencies
      - security
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"
      openai:
        patterns:
          - "openai"
          - "langchain-*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
